### ISSUE TITLE
Languagename is being redistributed to new owners without your consent

### ISSUE THREAD

**Issue by BieHDC** [mlemerre/l-lang#7]
See: https://github.com/microsoft/L/issues/1

**Comment by AnalogFeelings** [comment]
not sure if they are going to see this if the last commit was 8 years ago

**Comment by Entomy** [comment]
Worth a shot 🤷‍♂️

**Comment by vurvdev** [comment]
Now you guys killed it. Are you happy? :(

**Comment by BieHDC** [comment]
> Now you guys killed it. Are you happy? :(

They were probably afraid of getting sued.
Also closing this issue since its solved.

**Comment by mlemerre** [comment]
Thanks for the warning! The project is on stale (I have a lot of other ongoing projects, and Rust is a useful replacement for the language that I was designing, so I have less incentive to work on it, although I will probably do it one day). Microsoft never contacted me, so I guess they didn't care about the L name so much!

**Comment by Entomy** [comment]
@mlemerre If you'd potentially like some help implementing it in the future one day, feel free to hit me up. I've done a lot of work with language development and compilers, making it practically my life's work. I've got a compiler framework in development right now that I'm more than happy to help you use.

Regardless, cheers 🍻

**Comment by mlemerre** [comment]
Thanks Patrick! What was missing the most, IIRC, was low-level stuff and especially garbage collection. I would be happy to use your framework if it provides those!

**Comment by Entomy** [comment]
Garbage collection would be provided by the runtime library, not the compiler. [Boehm–Demers–Weiser](https://en.wikipedia.org/wiki/Boehm_garbage_collector) is one of the more common GC's, and has free implementations one could reuse. Essentially, the compiler would synthesize both machine code and some runtime library calls to make this work, but that's not unusual at all as there's plenty of other reasons to use a runtime library.

**Comment by mlemerre** [comment]
I see. You wrote "compiler framework" and I understood that as "language development framework". Intricate co-design of the GC with the compiler can yield better performance, but using the boehm GC is probably the easiest step.

**Comment by Entomy** [comment]
Semantics get weird. The framework is one for defining language analyzers (frontends) that are capable of sharing a common syntax tree with optional dynamically definable constructs (runtime syntax definition). This syntax tree can then be synthesized (compiled/interpreted). It does _not_ provide anything regarding the runtime library for the language in question; only the analyzer and synthesizer parts.

Yeah, I'd start with Boehm, and then once you have a working system in place you can investigate other options. Alternatively, you could consider options like how Ada handled storage pools or Zig handled allocators, where they're custom definable and can swap for no GC, or alternative GC's.

**Comment by Entomy** [comment]
I'm not sure if runtime libraries could be frameworked, but now I'm gonna be thinking about that all day. 🤔
